[env]
TARGET_TRIPLE = "thumbv6m-none-eabi"
FEATURES = ""

[tasks.build]
args = [
    "build",
    "@@remove-empty(BUILD_TYPE)",
    "--target",
    "${TARGET_TRIPLE}",
    "--features",
    "${FEATURES}",
]

[tasks.build-release]
clear = true
env.BUILD_TYPE = "--release"
run_task = "build"

[tasks.test]
disabled = true
